// <auto-generated />
namespace VSTDApp.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class secondCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(secondCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201702050036561_secondCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
